import type { SchoolYearDef } from "./types";

// Year 10 (ages 14-15, KS4, GCSE preparation). Topics are organised into a
// logical progressive sequence covering the GCSE Mathematics subject content
// common to Foundation and Higher tiers, as KS4 content is not prescribed by
// individual school year in the National Curriculum. A qualified mathematics
// teacher should review this sequence and pathway differentiation before
// publication (see DOCUMENTATION.md "Curriculum review"). All ten levels are
// fully authored, including Higher-tier question variants tagged
// pathway: "HIGHER" so they are only served to Higher learners. Every level's
// Mastery Challenge is generated for whichever pathway (Core / Foundation /
// Higher) the learner's profile has selected.
export const year10: SchoolYearDef = {
  yearNumber: 10,
  title: "Year 10",
  titleFr: "Année 10",
  keyStage: "KS4",
  summary: "GCSE Mathematics preparation for 14-15 year olds, with Foundation and Higher pathways.",
  summaryFr: "Préparation aux mathématiques du GCSE pour les 14-15 ans, avec les parcours Foundation et Higher.",
  minAge: 14,
  maxAge: 15,
  themeStage: "mature",
  levels: [
    { levelNumber: 1, title: "Number accuracy, bounds, indices, standard form and surds", titleFr: "Précision numérique, bornes, indices, notation scientifique et radicaux", summary: "By the end of this level, you will work accurately with bounds, indices, standard form and surds.", summaryFr: "À la fin de ce niveau, tu travailleras avec précision avec les bornes, les indices, la notation scientifique et les radicaux.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L1-1", description: "Calculate upper and lower bounds of numbers given to a degree of accuracy.", descriptionFr: "Calculer les bornes supérieure et inférieure de nombres donnés à un degré de précision.", dfeReference: "GCSE Number: bounds (Foundation & Higher)" },
      { code: "Y10-L1-2", description: "Calculate with roots and integer, fractional and negative indices.", descriptionFr: "Calculer avec des racines et des indices entiers, fractionnaires et négatifs.", dfeReference: "GCSE Number: indices (Foundation & Higher)" },
      { code: "Y10-L1-3", description: "Calculate with numbers in standard form, including on a calculator.", descriptionFr: "Calculer avec des nombres en notation scientifique, y compris à la calculatrice.", dfeReference: "GCSE Number: standard form (Foundation & Higher)" },
      { code: "Y10-L1-4", description: "Simplify surd expressions and rationalise a denominator (Higher extension).", descriptionFr: "Simplifier des expressions avec radicaux et rationaliser un dénominateur (extension Higher).", dfeReference: "GCSE Number: surds (Higher tier extension)" }
    ]},
    { levelNumber: 2, title: "Ratio, proportion, growth and compound measures", titleFr: "Rapports, proportionnalité, croissance et grandeurs composées", summary: "By the end of this level, you will solve GCSE-level problems involving ratio, proportion and growth.", summaryFr: "À la fin de ce niveau, tu résoudras des problèmes de niveau GCSE sur les rapports, la proportionnalité et la croissance.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L2-1", description: "Solve problems involving direct and inverse proportion, including algebraic representations.", descriptionFr: "Résoudre des problèmes de proportionnalité directe et inverse, y compris sous forme algébrique.", dfeReference: "GCSE Ratio & proportion: direct/inverse proportion" },
      { code: "Y10-L2-2", description: "Set up, solve and interpret the answers in growth and decay problems, including compound interest.", descriptionFr: "Poser, résoudre et interpréter des problèmes de croissance et de décroissance, y compris les intérêts composés.", dfeReference: "GCSE Ratio & proportion: growth and decay" },
      { code: "Y10-L2-3", description: "Convert between compound units, including speed, density and pressure (Higher extension: further compound measures).", descriptionFr: "Convertir entre grandeurs composées, dont la vitesse, la masse volumique et la pression (extension Higher : autres grandeurs composées).", dfeReference: "GCSE Ratio & proportion: compound units" }
    ]},
    { levelNumber: 3, title: "Algebraic expressions, equations, inequalities and sequences", titleFr: "Expressions, équations, inéquations et suites algébriques", summary: "By the end of this level, you will manipulate expressions and solve equations and inequalities at GCSE level.", summaryFr: "À la fin de ce niveau, tu manipuleras des expressions et tu résoudras des équations et des inéquations au niveau GCSE.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L3-1", description: "Simplify and manipulate algebraic expressions, including algebraic fractions (Higher extension).", descriptionFr: "Simplifier et manipuler des expressions algébriques, y compris des fractions algébriques (extension Higher).", dfeReference: "GCSE Algebra: manipulate expressions, algebraic fractions" },
      { code: "Y10-L3-2", description: "Solve linear and quadratic equations, including by factorising and using the quadratic formula.", descriptionFr: "Résoudre des équations linéaires et quadratiques, par factorisation et à l'aide de la formule quadratique.", dfeReference: "GCSE Algebra: solve linear/quadratic equations" },
      { code: "Y10-L3-3", description: "Generate terms of a sequence and deduce expressions for the nth term of linear and quadratic sequences.", descriptionFr: "Générer les termes d'une suite et déduire l'expression du terme de rang n de suites arithmétiques et quadratiques.", dfeReference: "GCSE Algebra: nth term of sequences" }
    ]},
    { levelNumber: 4, title: "Quadratics and simultaneous equations", titleFr: "Équations quadratiques et systèmes d'équations", summary: "By the end of this level, you will solve quadratic and simultaneous equations.", summaryFr: "À la fin de ce niveau, tu résoudras des équations quadratiques et des systèmes d'équations.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L4-1", description: "Solve quadratic equations algebraically by factorising, completing the square (Higher) and using the formula.", descriptionFr: "Résoudre algébriquement des équations quadratiques par factorisation, par complétion du carré (Higher) et à l'aide de la formule.", dfeReference: "GCSE Algebra: solve quadratic equations" },
      { code: "Y10-L4-2", description: "Solve two simultaneous equations in two variables, linear/linear and linear/quadratic (Higher).", descriptionFr: "Résoudre deux équations simultanées à deux inconnues, linéaire/linéaire et linéaire/quadratique (Higher).", dfeReference: "GCSE Algebra: solve simultaneous equations" },
      { code: "Y10-L4-3", description: "Find approximate solutions to equations using a graph.", descriptionFr: "Trouver des solutions approchées d'équations à l'aide d'un graphique.", dfeReference: "GCSE Algebra: approximate solutions using a graph" }
    ]},
    { levelNumber: 5, title: "Graphs, functions and graphical interpretation", titleFr: "Graphiques, fonctions et interprétation graphique", summary: "By the end of this level, you will plot, sketch and interpret a range of graphs and functions.", summaryFr: "À la fin de ce niveau, tu traceras, esquisseras et interpréteras divers graphiques et fonctions.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L5-1", description: "Plot and interpret graphs of linear, quadratic and simple cubic functions.", descriptionFr: "Tracer et interpréter les graphiques de fonctions linéaires, quadratiques et cubiques simples.", dfeReference: "GCSE Algebra: plot/interpret graphs" },
      { code: "Y10-L5-2", description: "Interpret the gradient of a straight line as a rate of change and calculate rates of change from graphs.", descriptionFr: "Interpréter le coefficient directeur d'une droite comme un taux de variation et calculer des taux de variation à partir de graphiques.", dfeReference: "GCSE Algebra: gradient as rate of change" },
      { code: "Y10-L5-3", description: "Recognise and interpret graphs that illustrate direct and inverse proportion.", descriptionFr: "Reconnaître et interpréter les graphiques illustrant la proportionnalité directe et inverse.", dfeReference: "GCSE Ratio & proportion: proportion graphs" }
    ]},
    { levelNumber: 6, title: "Geometry, constructions, congruence and similarity", titleFr: "Géométrie, constructions, isométrie et similitude", summary: "By the end of this level, you will apply geometric reasoning, constructions, congruence and similarity.", summaryFr: "À la fin de ce niveau, tu appliqueras le raisonnement géométrique, les constructions, l'isométrie et la similitude.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L6-1", description: "Apply the conditions for congruent triangles (SSS, SAS, ASA, RHS).", descriptionFr: "Appliquer les conditions d'isométrie des triangles (SSS, SAS, ASA, RHS).", dfeReference: "GCSE Geometry & measures: congruence conditions" },
      { code: "Y10-L6-2", description: "Use similarity to find missing lengths, areas and volumes of similar shapes.", descriptionFr: "Utiliser la similitude pour trouver des longueurs, des aires et des volumes manquants de figures semblables.", dfeReference: "GCSE Geometry & measures: similarity" },
      { code: "Y10-L6-3", description: "Use geometric reasoning to construct mathematical arguments and proofs.", descriptionFr: "Utiliser le raisonnement géométrique pour construire des arguments et des démonstrations mathématiques.", dfeReference: "GCSE Geometry & measures: reasoning and proof" }
    ]},
    { levelNumber: 7, title: "Pythagoras and trigonometry", titleFr: "Pythagore et trigonométrie", summary: "By the end of this level, you will apply Pythagoras' theorem and trigonometry, including the sine and cosine rules (Higher).", summaryFr: "À la fin de ce niveau, tu appliqueras le théorème de Pythagore et la trigonométrie, y compris les lois des sinus et des cosinus (Higher).", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L7-1", description: "Apply Pythagoras' theorem and trigonometric ratios in right-angled triangles in 2D and simple 3D contexts.", descriptionFr: "Appliquer le théorème de Pythagore et les rapports trigonométriques dans des triangles rectangles, en 2D et en 3D simple.", dfeReference: "GCSE Geometry & measures: Pythagoras and trigonometry" },
      { code: "Y10-L7-2", description: "Know and apply the sine rule, cosine rule and area of a triangle formula in non-right-angled triangles (Higher extension).", descriptionFr: "Connaître et appliquer la loi des sinus, la loi des cosinus et la formule de l'aire d'un triangle dans des triangles quelconques (extension Higher).", dfeReference: "GCSE Geometry & measures: sine/cosine rule (Higher tier)" },
      { code: "Y10-L7-3", description: "Know exact trigonometric values for key angles (0, 30, 45, 60, 90 degrees).", descriptionFr: "Connaître les valeurs trigonométriques exactes des angles clés (0, 30, 45, 60 et 90 degrés).", dfeReference: "GCSE Geometry & measures: exact trigonometric values" }
    ]},
    { levelNumber: 8, title: "Circles, vectors, area, surface area and volume", titleFr: "Cercles, vecteurs, aire, aire totale et volume", summary: "By the end of this level, you will calculate area, surface area and volume, and use vectors.", summaryFr: "À la fin de ce niveau, tu calculeras l'aire, l'aire totale et le volume, et tu utiliseras les vecteurs.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L8-1", description: "Calculate perimeter, area, surface area and volume of a range of 2D and 3D shapes, including circles and spheres.", descriptionFr: "Calculer le périmètre, l'aire, l'aire totale et le volume de diverses figures 2D et 3D, y compris les cercles et les sphères.", dfeReference: "GCSE Geometry & measures: perimeter/area/surface area/volume" },
      { code: "Y10-L8-2", description: "Describe translations using vectors, and add/subtract vectors and multiply a vector by a scalar.", descriptionFr: "Décrire des translations à l'aide de vecteurs, additionner et soustraire des vecteurs et multiplier un vecteur par un scalaire.", dfeReference: "GCSE Geometry & measures: vectors" },
      { code: "Y10-L8-3", description: "Use vector methods to construct geometric arguments and proofs (Higher extension).", descriptionFr: "Utiliser les méthodes vectorielles pour construire des arguments et des démonstrations géométriques (extension Higher).", dfeReference: "GCSE Geometry & measures: vector proofs (Higher tier)" }
    ]},
    { levelNumber: 9, title: "Probability, sampling and statistics", titleFr: "Probabilités, échantillonnage et statistiques", summary: "By the end of this level, you will calculate probabilities, evaluate sampling methods and interpret statistics.", summaryFr: "À la fin de ce niveau, tu calculeras des probabilités, tu évalueras des méthodes d'échantillonnage et tu interpréteras des statistiques.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L9-1", description: "Calculate and interpret conditional probability through representation using tree diagrams and Venn diagrams.", descriptionFr: "Calculer et interpréter des probabilités conditionnelles à l'aide d'arbres de probabilité et de diagrammes de Venn.", dfeReference: "GCSE Probability: conditional probability" },
      { code: "Y10-L9-2", description: "Evaluate methods of sampling in the context of a statistical investigation.", descriptionFr: "Évaluer les méthodes d'échantillonnage dans le cadre d'une enquête statistique.", dfeReference: "GCSE Statistics: sampling methods" },
      { code: "Y10-L9-3", description: "Interpret and construct cumulative frequency diagrams and box plots, and calculate/interpret the interquartile range (Higher extension).", descriptionFr: "Interpréter et construire des diagrammes de fréquences cumulées et des boîtes à moustaches, et calculer et interpréter l'écart interquartile (extension Higher).", dfeReference: "GCSE Statistics: cumulative frequency/box plots (Higher tier)" }
    ]},
    { levelNumber: 10, title: "Year 10 GCSE-style mixed mastery", titleFr: "Maîtrise mixte de l'Année 10, façon GCSE", summary: "By the end of this level, you will confidently apply GCSE-style reasoning across number, algebra, geometry, probability and statistics.", summaryFr: "À la fin de ce niveau, tu appliqueras avec assurance le raisonnement de type GCSE au nombre, à l'algèbre, à la géométrie, aux probabilités et aux statistiques.", isMixedMastery: true, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y10-L10-1", description: "Use number, ratio and proportion fluently in GCSE-style calculations.", descriptionFr: "Utiliser avec aisance le nombre, les rapports et la proportionnalité dans des calculs de type GCSE.", dfeReference: "GCSE Number / Ratio & proportion (mixed review)" },
      { code: "Y10-L10-2", description: "Apply algebraic manipulation, equations, sequences and graphs to solve multi-step GCSE-style problems.", descriptionFr: "Appliquer la manipulation algébrique, les équations, les suites et les graphiques pour résoudre des problèmes de type GCSE à étapes multiples.", dfeReference: "GCSE Algebra (mixed review)" },
      { code: "Y10-L10-3", description: "Use geometry, trigonometry, probability and statistics in GCSE-style reasoning questions.", descriptionFr: "Utiliser la géométrie, la trigonométrie, les probabilités et les statistiques dans des questions de raisonnement de type GCSE.", dfeReference: "GCSE Geometry & measures / Probability / Statistics (mixed review)" }
    ]}
  ]
};
