import type { SchoolYearDef } from "./types";

// Year 5 (ages 9-10, KS2). Level 1 is fully authored (lessons, practice,
// 40-question mastery bank); levels 2-10 are scaffolded (curriculum metadata
// only — see questionEngine/templates/all.ts COMPLETE_LEVEL_KEYS).
export const year5: SchoolYearDef = {
  yearNumber: 5,
  title: "Year 5",
  titleFr: "Année 5",
  keyStage: "KS2",
  summary: "Large numbers, percentages and volume for 9-10 year olds.",
  summaryFr: "Les grands nombres, les pourcentages et le volume pour les enfants de 9 à 10 ans.",
  minAge: 9,
  maxAge: 10,
  themeStage: "adventure",
  levels: [
    { levelNumber: 1, title: "Place value to 1,000,000, rounding and negative numbers", titleFr: "Valeur de position jusqu’à 1 000 000, arrondi et nombres négatifs", summary: "By the end of this level, you will read, write and round numbers to 1,000,000, including negative numbers.", summaryFr: "À la fin de ce niveau, tu sauras lire, écrire et arrondir les nombres jusqu’à 1 000 000, y compris les nombres négatifs.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L1-1", description: "Read, write, order and compare numbers to at least 1,000,000.", descriptionFr: "Lire, écrire, ranger et comparer les nombres jusqu’à au moins 1 000 000.", dfeReference: "Y5 Number & place value: read/write/order/compare numbers to 1,000,000" },
      { code: "Y5-L1-2", description: "Round any number up to 1,000,000 to a required degree of accuracy.", descriptionFr: "Arrondir n’importe quel nombre jusqu’à 1 000 000 au degré de précision demandé.", dfeReference: "Y5 Number & place value: round any number up to 1,000,000" },
      { code: "Y5-L1-3", description: "Interpret negative numbers in context, counting forwards and backwards through zero.", descriptionFr: "Interpréter les nombres négatifs en contexte, en comptant en avant et en arrière à travers zéro.", dfeReference: "Y5 Number & place value: interpret negative numbers in context" }
    ]},
    { levelNumber: 2, title: "Addition, subtraction and multi-step problems", titleFr: "Addition, soustraction et problèmes à étapes multiples", summary: "By the end of this level, you will add and subtract large numbers and solve multi-step problems.", summaryFr: "À la fin de ce niveau, tu sauras additionner et soustraire de grands nombres et résoudre des problèmes à étapes multiples.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L2-1", description: "Add and subtract whole numbers with more than 4 digits using formal written methods.", descriptionFr: "Additionner et soustraire des nombres entiers de plus de 4 chiffres avec des méthodes posées.", dfeReference: "Y5 Addition & subtraction: formal written methods" },
      { code: "Y5-L2-2", description: "Use rounding to check answers and determine levels of accuracy.", descriptionFr: "Utiliser l’arrondi pour vérifier les réponses et déterminer le niveau de précision.", dfeReference: "Y5 Addition & subtraction: use rounding to check answers" },
      { code: "Y5-L2-3", description: "Solve multi-step addition and subtraction problems, deciding which operations and methods to use.", descriptionFr: "Résoudre des problèmes d’addition et de soustraction à étapes multiples, en choisissant les opérations et méthodes à utiliser.", dfeReference: "Y5 Addition & subtraction: solve multi-step problems" }
    ]},
    { levelNumber: 3, title: "Multiplication and division", titleFr: "Multiplication et division", summary: "By the end of this level, you will multiply and divide numbers using formal written methods.", summaryFr: "À la fin de ce niveau, tu sauras multiplier et diviser des nombres avec des méthodes posées.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L3-1", description: "Multiply numbers up to 4 digits by a one- or two-digit number using a formal written method.", descriptionFr: "Multiplier des nombres jusqu’à 4 chiffres par un nombre à un ou deux chiffres avec une méthode posée.", dfeReference: "Y5 Multiplication & division: formal written method" },
      { code: "Y5-L3-2", description: "Divide numbers up to 4 digits by a one-digit number, interpreting remainders appropriately.", descriptionFr: "Diviser des nombres jusqu’à 4 chiffres par un nombre à un chiffre, en interprétant correctement les restes.", dfeReference: "Y5 Multiplication & division: divide, interpreting remainders" },
      { code: "Y5-L3-3", description: "Multiply and divide whole numbers by 10, 100 and 1,000.", descriptionFr: "Multiplier et diviser des nombres entiers par 10, 100 et 1 000.", dfeReference: "Y5 Multiplication & division: multiply/divide by 10, 100, 1000" }
    ]},
    { levelNumber: 4, title: "Factors, multiples, primes, squares and cubes", titleFr: "Diviseurs, multiples, nombres premiers, carrés et cubes", summary: "By the end of this level, you will identify factors, multiples, prime, square and cube numbers.", summaryFr: "À la fin de ce niveau, tu sauras identifier les diviseurs, multiples, nombres premiers, carrés et cubes.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L4-1", description: "Identify multiples and factors, including finding all factor pairs of a number.", descriptionFr: "Identifier les multiples et diviseurs, y compris trouver toutes les paires de diviseurs d’un nombre.", dfeReference: "Y5 Multiplication & division: identify multiples and factors" },
      { code: "Y5-L4-2", description: "Know and use the vocabulary of prime numbers and establish whether a number up to 100 is prime.", descriptionFr: "Connaître et utiliser le vocabulaire des nombres premiers et déterminer si un nombre jusqu’à 100 est premier.", dfeReference: "Y5 Multiplication & division: prime numbers" },
      { code: "Y5-L4-3", description: "Recognise and use square numbers and cube numbers and their notation.", descriptionFr: "Reconnaître et utiliser les nombres carrés et cubes ainsi que leur notation.", dfeReference: "Y5 Multiplication & division: square and cube numbers" }
    ]},
    { levelNumber: 5, title: "Fractions and mixed numbers", titleFr: "Fractions et nombres fractionnaires", summary: "By the end of this level, you will compare, add and subtract fractions, including mixed numbers.", summaryFr: "À la fin de ce niveau, tu sauras comparer, additionner et soustraire des fractions, y compris des nombres fractionnaires.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L5-1", description: "Compare and order fractions whose denominators are multiples of the same number.", descriptionFr: "Comparer et ranger des fractions dont les dénominateurs sont des multiples d’un même nombre.", dfeReference: "Y5 Fractions: compare/order fractions" },
      { code: "Y5-L5-2", description: "Add and subtract fractions with the same denominator, including mixed numbers.", descriptionFr: "Additionner et soustraire des fractions de même dénominateur, y compris des nombres fractionnaires.", dfeReference: "Y5 Fractions: add/subtract fractions and mixed numbers" },
      { code: "Y5-L5-3", description: "Multiply proper fractions and mixed numbers by whole numbers.", descriptionFr: "Multiplier des fractions propres et des nombres fractionnaires par des nombres entiers.", dfeReference: "Y5 Fractions: multiply proper fractions/mixed numbers by whole numbers" }
    ]},
    { levelNumber: 6, title: "Decimals and percentages", titleFr: "Décimaux et pourcentages", summary: "By the end of this level, you will convert between fractions, decimals and percentages.", summaryFr: "À la fin de ce niveau, tu sauras convertir entre fractions, décimaux et pourcentages.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L6-1", description: "Read, write, order and compare numbers with up to three decimal places.", descriptionFr: "Lire, écrire, ranger et comparer des nombres avec jusqu’à trois décimales.", dfeReference: "Y5 Decimals: read/write/order/compare with up to 3dp" },
      { code: "Y5-L6-2", description: "Recognise the per cent symbol and understand percentage as parts per hundred.", descriptionFr: "Reconnaître le symbole pourcentage et comprendre le pourcentage comme des parts sur cent.", dfeReference: "Y5 Percentages: recognise % and parts per hundred" },
      { code: "Y5-L6-3", description: "Round decimals with two decimal places to the nearest whole number and one decimal place.", descriptionFr: "Arrondir des nombres à deux décimales à l’unité la plus proche et à une décimale.", dfeReference: "Y5 Decimals: round decimals with 2dp" }
    ]},
    { levelNumber: 7, title: "Measurement, perimeter, area and volume", titleFr: "Mesures, périmètre, aire et volume", summary: "By the end of this level, you will calculate area, perimeter and volume using formulae.", summaryFr: "À la fin de ce niveau, tu sauras calculer l’aire, le périmètre et le volume à l’aide de formules.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L7-1", description: "Calculate the area of rectangles and estimate area of irregular shapes.", descriptionFr: "Calculer l’aire de rectangles et estimer l’aire de formes irrégulières.", dfeReference: "Y5 Measurement: calculate area of rectangles" },
      { code: "Y5-L7-2", description: "Estimate volume and capacity using cubes and standard units.", descriptionFr: "Estimer le volume et la capacité à l’aide de cubes et d’unités standard.", dfeReference: "Y5 Measurement: estimate volume and capacity" },
      { code: "Y5-L7-3", description: "Convert between different units of metric measure.", descriptionFr: "Convertir entre différentes unités de mesure métrique.", dfeReference: "Y5 Measurement: convert between units of metric measure" }
    ]},
    { levelNumber: 8, title: "Angles, shapes, coordinates and transformations", titleFr: "Angles, formes, coordonnées et transformations", summary: "By the end of this level, you will measure angles and reflect/translate shapes.", summaryFr: "À la fin de ce niveau, tu sauras mesurer des angles et faire des réflexions/translations de formes.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L8-1", description: "Know angles are measured in degrees; estimate and compare acute, obtuse and reflex angles.", descriptionFr: "Savoir que les angles se mesurent en degrés ; estimer et comparer les angles aigus, obtus et rentrants.", dfeReference: "Y5 Geometry: know angles are measured in degrees" },
      { code: "Y5-L8-2", description: "Identify, describe and represent the position of a shape following reflection or translation.", descriptionFr: "Identifier, décrire et représenter la position d’une forme après une réflexion ou une translation.", dfeReference: "Y5 Geometry: reflection and translation" },
      { code: "Y5-L8-3", description: "Use the properties of rectangles to deduce related facts and find missing lengths and angles.", descriptionFr: "Utiliser les propriétés des rectangles pour déduire des faits liés et trouver des longueurs et angles manquants.", dfeReference: "Y5 Geometry: use properties of rectangles" }
    ]},
    { levelNumber: 9, title: "Statistics, line graphs and timetables", titleFr: "Statistiques, graphiques en ligne et horaires", summary: "By the end of this level, you will read line graphs, tables and timetables.", summaryFr: "À la fin de ce niveau, tu sauras lire des graphiques en ligne, des tableaux et des horaires.", isMixedMastery: false, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L9-1", description: "Solve comparison, sum and difference problems using information presented in a line graph.", descriptionFr: "Résoudre des problèmes de comparaison, de somme et de différence à partir d’informations présentées dans un graphique en ligne.", dfeReference: "Y5 Statistics: solve problems using line graphs" },
      { code: "Y5-L9-2", description: "Complete, read and interpret information in tables, including timetables.", descriptionFr: "Compléter, lire et interpréter des informations dans des tableaux, y compris des horaires.", dfeReference: "Y5 Statistics: complete/read/interpret tables including timetables" },
      { code: "Y5-L9-3", description: "Calculate durations using 24-hour clock timetables.", descriptionFr: "Calculer des durées à partir d’horaires en format 24 heures.", dfeReference: "Y5 Measurement/Statistics: 24-hour clock and timetables" }
    ]},
    { levelNumber: 10, title: "Year 5 mixed mastery", titleFr: "Maîtrise mixte — Année 5", summary: "By the end of this level, you will confidently use everything you have learned in Year 5.", summaryFr: "À la fin de ce niveau, tu utiliseras avec assurance tout ce que tu as appris en Année 5.", isMixedMastery: true, status: "COMPLETE", pathway: null, objectives: [
      { code: "Y5-L10-1", description: "Use place value, negative numbers and the four operations with large numbers.", descriptionFr: "Utiliser la valeur de position, les nombres négatifs et les quatre opérations avec de grands nombres.", dfeReference: "Y5 Number & Addition/subtraction (mixed review)" },
      { code: "Y5-L10-2", description: "Apply factors, multiples, fractions, decimals and percentages in problems.", descriptionFr: "Utiliser les diviseurs, multiples, fractions, décimaux et pourcentages dans des problèmes.", dfeReference: "Y5 Multiplication/division, Fractions, Decimals & Percentages (mixed review)" },
      { code: "Y5-L10-3", description: "Use area, volume, angles, transformations and statistics accurately.", descriptionFr: "Utiliser l’aire, le volume, les angles, les transformations et les statistiques avec précision.", dfeReference: "Y5 Measurement, Geometry & Statistics (mixed review)" }
    ]}
  ]
};
